### ISSUE TITLE
WithinProjection

### ISSUE THREAD

**Issue by unc-quite** [mrvux/dx11-vvvv#112]
WithinProjection (DX11.Layer) works as dx9 WithinViewport (Transform)

makes it impossible to render stuff partially (with viewports), if there is anything that uses WithinProjection (DX11.Layer)

**Comment by mrvux** [comment]
Ok that's rather late for this one, but here we are:
https://github.com/mrvux/dx11-vvvv/commit/6fe016746d5b42b249c594d76e29baccc23e6a53

Has options to preserve aspect/crop, so basically:
-Both preserve Off (default) = WithinViewport (so we avoid breaking change)
-Aspect Off, Crop On = WithinNormalizedProjection
-Both On = WithinProjection (as per DX9)
