### ISSUE TITLE
some fonts not working

### ISSUE THREAD

**Issue by unc-quite** [mrvux/dx11-vvvv#123]
like this one for example: https://dl.dropboxusercontent.com/u/23860719/Glober%20Family.zip
not working with dx11, but in dx9 or in string iobox it works fine

**Comment by ndrv** [comment]
Hey guys, is there some news about that issue? I'm encountering the same problem. Installed one font family which is visible/selectable in 'Text (DX11.Layer)' node but is not showing the right font, instead choosing some standard looking one. Is there some workaround or some non-official version of this node to get it running? thx!

**Comment by PRonnenberg** [comment]
A bit late. But I ran into the same issue and it seems that the directwrite nodes only take regular fonts. So I changed the font I wanted to use to a regular one, using a font conversion tool such as truetype. Then it worked out. A bit of fiddling and try & error, so just a workaround.

**Comment by mrvux** [comment]
Updated enum is last dx build to use DirectWrite family (opposed to 4v font names).
Now right fonts are in the list
