### ISSUE TITLE
filestream vlc crashes

### ISSUE THREAD

**Issue by catvvvveasel** [mrvux/dx11-vvvv#146]
I had numerous crashes with file stream vlc, caused by switching files, switching to a non existent file was worse, but simply switching did it too. All files are mjpg, I also had an issue creating more than a certain number of file streams, not sure what this number was, when I encountered it, I moved all the file streams to a sub patch and started switching the input files, causing the crashes above.
Exceptions are not thrown, I simply get a vvvv.exe has stopped working.
Also dx11 renders are still white on creation, so I had a rather lovely 15k lumen white wash at the gig!
The crashes happen after a variable length of time, I thought I'd got it down to 1 in a hundred changes, but then had it happen on the 1st change of the show. I'll try and put together a demo of this again.

**Comment by mrvux** [comment]
Ok since no feed on that and could not repro, closing.
