### ISSUE TITLE
ATI doesn't support Channel Count 3 on DynamicTexture

### ISSUE THREAD

**Issue by elliotwoods** [mrvux/dx11-vvvv#162]
You get erratic results, but basically it kind of treats the inputs like a 4 channel texture

**Comment by mrvux** [comment]
Yes pretty much so, also please note that nvidia kinda fixes it "under the hood" (spits you a warning in debug runtime), did not try on intel but would expect either a black screen/driver crash too.

https://github.com/mrvux/dx11-vvvv/commit/dca0cf3ee0b2fd7e47aa2bc135392504d9cc70df Now runtime will send you a warning if you try 3 channels

If you expect and now how to use 3 channel textures
https://github.com/mrvux/dx11-vvvv/commit/755d7bf037679a42f14acde649b72ec73f74b067

Option to disable warning (to save spam)
