### ISSUE TITLE
AsSharedTexture cpu hit

### ISSUE THREAD

**Issue by catvvvveasel** [mrvux/dx11-vvvv#172]
In debug mode asshared texture seems to use much cpu and drops my frame rate by quite a bit, I'm sure the clicks may be affected the same as my pipet complaints in previous posts, but the fps drop seems excessive.
As I understood it, shared memory is just a pointer to the memory location of the texture, so why do we need a node rather than just a pointer? Setting evaluate to 0 on the assharedtexture stops the sharing, so its definitely doing something rather than just being a pointer, and info(dx11) pointer does work for sharing either. Is there something I don't understand here?

**Comment by mrvux** [comment]
Shared resources do a lot more than just a pointer, so they have a cost (pipeline flushes, cross process synchronization), so overhead is there and it's up to user to take it or not.
