### ISSUE TITLE
Feature : S+H for GPU assets

### ISSUE THREAD

**Issue by elliotwoods** [mrvux/dx11-vvvv#177]
It's be great to have S+H for:
- `DX11.Texture2D`, etc
- `StructuredBuffer<T>`

Especially for `DX11.Texture2D`. For many purposes (single slice), having an interim renderer works, but isn't perfect.

**Comment by mrvux** [comment]
https://github.com/mrvux/dx11-vvvv/commit/8d721bdaac06f1c939b4e052257a07493cd3f82e 

S+H for texture2d/3d and structuredbuffer (any version) 

Also automatically block upwards rendering when off, Non spreadable
