### ISSUE TITLE
x86 builds OK, x64 fails missing MemoryIOStream

### ISSUE THREAD

**Issue by mediadog** [mrvux/dx11-vvvv#182]
Did a fresh clone and build today to try and get the Kinect2 working again, and while the x86 builds clean, x64 gives:

Error	4	The type or namespace name 'MemoryIOStream' could not be found (are you missing a using directive or an assembly reference?)	D:\newdx11\dx11-vvvv\Core\VVVV.DX11.Lib\RenderGraph\Pins\DX11ResourceInputPin.cs	16	50	VVVV.DX11.Lib
Error	5	The type or namespace name 'MemoryIOStream' could not be found (are you missing a using directive or an assembly reference?)	D:\newdx11\dx11-vvvv\Core\VVVV.DX11.Lib\RenderGraph\Pins\DX11ResourceOutputPin.cs	18	51	VVVV.DX11.Lib

**Comment by mrvux** [comment]
Build instructions updated
