### ISSUE TITLE
Resizing Renderer Dx Window Doesnt update its resolution

### ISSUE THREAD

**Issue by catvvvveasel** [mrvux/dx11-vvvv#183]
The actually buffer size reports the size correctly but the render needs to be reloaded to update the contents correctly.
Drag a corner of the window, and the perf meter will stay the same relative size, and if you scale far enough content will become pixelated. Delete and undo to get the correct backbuffer size

**Comment by catvvvveasel** [comment]
Ah! I've just been working on a patch, I enabled Present upfront in the main loop, and the resolution didnt update on fullscreen, turned it off, and it did!

**Comment by mrvux** [comment]
Works in both cases here, no idea what this present up front does (guess some random hack that was needed once and stayed as legacy), still never managed to replicate that one.
