### ISSUE TITLE
kinect v1 IR light not starting consistently

### ISSUE THREAD

**Issue by sunep** [mrvux/dx11-vvvv#187]
I am having some trouble getting consistent behavior from one the original kinect.

It will not consistently turn on´, meaning that it actually starts and I can see it as started, but the IR light is not on and the skeleton tracking is not working.

Other times it works.

System is win7 x64 with beta33.3x86 and DX11 is version: vvvv-packs-dx11-b33x-x86

any suggestions?

Sune

also in this thread: http://vvvv.org/forum/dx11-kinect-v1-ir-light-not-starting-consistently

**Comment by mrvux** [comment]
Ok since went into forum post and seen it was version issue/solved, closing it here as well :)
