### ISSUE TITLE
Sampler not being updated

### ISSUE THREAD

**Issue by unc-quite** [mrvux/dx11-vvvv#189]
when renderer is disabled, this happens with shader nodes, but strangely not with others, like Quad (DX11.Layer)
https://dl.dropboxusercontent.com/u/23860719/SamplerUpdateBug.v4p

**Comment by mrvux** [comment]
Bit of a tricky one, since the Pin.Changed attribute was one frame too late and shader misses it.
Fixed in https://github.com/mrvux/dx11-vvvv/commit/cb10711f55ee7ea05491e28ede046b072d3415c8
