### ISSUE TITLE
Shader parsing sneaky error

### ISSUE THREAD

**Issue by unc-quite** [mrvux/dx11-vvvv#190]
https://dl.dropboxusercontent.com/u/23860719/ShaderParsingWTF.zip
with some combination of comments, shader does not get updated on code change+save (and also node becomes red)

**Comment by mrvux** [comment]
Definitely a sneaky one, https://github.com/mrvux/dx11-vvvv/commit/174aaa9d658f007358fb9f899a51ed30f5541bf8

Comment order removal was getting rid of the whole thing.

Please note that I fixed that here, but vvvv sdk does the same, so actually your shader is also registered as a dx9 one, so it needs a fix on vvvv side too
