### ISSUE TITLE
TextureFX_DefaultSize non spreadable

### ISSUE THREAD

**Issue by colorsound** [mrvux/dx11-vvvv#195]
TextureFX defaultsize seems to take only first res you input for all the spread of textures so not spreable feature. it would be great to have it spreable as textureFx accepts diferent res per texture. cheers

**Comment by mrvux** [comment]
Added in https://github.com/mrvux/dx11-vvvv/commit/56fc6ac37b755b184a15285f74dc9e0ee41fa3b6
