### ISSUE TITLE
gsfx with nil input freezes v4

### ISSUE THREAD

**Issue by unc-quite** [mrvux/dx11-vvvv#196]
when NIL comes to View or Projection input of a gsfx (which seems to happen if aspectratio in projection matrix is calculated from a value coming out of renderer window), vvvv freezes
https://dl.dropboxusercontent.com/u/23860719/Subdivide_GSFX_NIL_BUG.zip

**Comment by mrvux** [comment]
Fixed in https://github.com/mrvux/dx11-vvvv/commit/e3e5deae399f244ffae2e5da32b8fa34195e80fe 
Thanks !
