### ISSUE TITLE
repo clone problem

### ISSUE THREAD

**Issue by wirmachenbunt** [mrvux/dx11-vvvv#197]
see screenshot, its probably just me being stupid
![clone](https://cloud.githubusercontent.com/assets/1138673/5978969/fa731a7c-a8a3-11e4-9210-112b13683d27.PNG)

**Comment by mrvux** [comment]
Don't forget to clone master (which is current, alphatest i need to remove it, very old branch).

Also you need to create a fork before to clone

**Comment by mrvux** [comment]
Ok removed old branches and fixed documentation
