### ISSUE TITLE
renderer black after reopening patchs

### ISSUE THREAD

**Issue by yokailab** [mrvux/dx11-vvvv#199]
hi mrvux,
i'm not very good with dx11. few times happen to me that after i close dx11 patch and open another or the same one, the renderers appear black. all will work fine if i restart vvvv. couldn't find logic between which patches it occours, seems like all. 
I'm running vvvv_45beta33.3_x86, packs from 10.9.14, on windows 7, ATI Radeon HD 5830 Graphics.
would be nice if there easy trick for that.
thanks,
shaul

**Comment by mrvux** [comment]
Some sample would be needed, without it, pretty hard to know what's going on

**Comment by yokailab** [comment]
I understand it's hard to say, but no specific patch for sample, because it happen with all dx11 patches. In certain point after working  a while the renderer appears black. all will work properly on restart vvvv. Could'nt find any certain action that causing it to happen. Thanks anyway, maybe I show you this at Node.

**Comment by mrvux** [comment]
Not gonna be able to help much without a sample, so closing for now.
