### ISSUE TITLE
Feature Request: Text Kerning Spacing

### ISSUE THREAD

**Issue by ethermammoth** [mrvux/dx11-vvvv#205]
Hi mrvux, 

any chance to implement Justification, Kerning, and Spacing as off:
https://msdn.microsoft.com/en-us/library/windows/desktop/hh994452(v=vs.85).aspx

As they write it only would work on windows 8, but is there a chance to implement it in some way?
That would finally be another reason (except kinect2) to use windows8. 

I really like the font rendering quality in dx11, but crappy designers always use custom kerning and spacing to make my life harder...

**Comment by mrvux** [comment]
Didn't see that, yeah could be possible to add, but issue is SlimDX is likely not up to date for it.

**Comment by mrvux** [comment]
Can't do that against slimdx, as the wrapper is not up to date along any win8/win8+ new features, so that would be a larger set of work.

**Comment by mrvux** [comment]
Ok with new style interface it's rather simple to add those.
I got spacing working, same as justification, but don't have a font with kerning enabled so if you could post one here would be cool to test

**Comment by mrvux** [comment]
Nevermind, found one, so will push commit soon ;)

**Comment by mrvux** [comment]
Now in latest 0.6.1 build, enum changes for justification, and KerningPair+spacing nodes in there.
