### ISSUE TITLE
Screenshot links in Readme.md broken

### ISSUE THREAD

**Issue by mediadog** [mrvux/dx11-vvvv#208]
Clicking on the links for the Visual Studio configuration screenshots in the Readme.md as displayed by github gets a "Not found".

**Comment by mediadog** [comment]
In addition, trying to directly access the link:

https://raw.githubusercontent.com/mrvux/dx11-vvvv/alphatest/images/OpenConfigurationManager.png

from the Readme.md file gets:
The image “https://raw.githubusercontent.com/mrvux/dx11-vvvv/alphatest/images/OpenConfigurationManager.png” cannot be displayed because it contains errors.

Ditto for the remaining two links as well.  The files located in the images folder when directly accessed display fine, however.

**Comment by mrvux** [comment]
Fixed, they were taking alphatest branch (which has been removed) , instead of master
