### ISSUE TITLE
Feature request: force mips on tfx

### ISSUE THREAD

**Issue by unc-quite** [mrvux/dx11-vvvv#212]
Mipmaps are not generated by default, yet still they are often useful, but modifying tfx code each time is a pain. Would be great to have an option to force mipmap generation on the latest pass of the tfx

**Comment by mrvux** [comment]
You can do that already using <bool mips=true;> on a pass, so just need to be added on last pass

**Comment by unc-quite** [comment]
yeah i mean do to it from a patch  (via toggle pin), so even if a tfx doesn't have mips=true on last pass, it would still be able to generate mipmaps

**Comment by mrvux** [comment]
This has been added in https://github.com/mrvux/dx11-vvvv/commit/c5be1b254a10f86f7de1a7ca1fa6c670ac622fe8
