### ISSUE TITLE
Mesh messing up Bone Names

### ISSUE THREAD

**Issue by jhnnslmk** [mrvux/dx11-vvvv#216]
Hey vux,

Mesh (DX11.Geometry Assimp) messes up the bone names for my file somehow.
SceneExplorer and Node (Assimp) still doing fine, but Node-Output-order doesn't match the MeshNode Bones Matrices, so not really working as a workaround (got the names fixed in an IOBox for the time being, loaded fine from a .fbx file ... which had the matrices wrong ;) - so I puzzled the working parts together).

Hit me up on Skype if you need the .dae file ... name's jlemke_

![schnappschuss_062315_022405_pm](https://cloud.githubusercontent.com/assets/1488726/8305891/81ba4868-19b3-11e5-818f-490bd1de8cfd.jpg)

**Comment by mrvux** [comment]
Scene and bones list are different, since scene is a tree hierarchy, so it's in now way guaranteed that order is preserved (actually it's even unlikely that it would even happen).
You need to query Nodes from bone names.
