### ISSUE TITLE
kinect2 prepose

### ISSUE THREAD

**Issue by circuitb** [mrvux/dx11-vvvv#217]
hey,

when loading the example .app file (ballet.app) in the prepose node 
the "valid" pin stick to 0
any ideas??

**Comment by mrvux** [comment]
Not sure if all dlls are copied at the moment.
Also not certain will keep that node for next release, since I didn't really see any update on this project, so not sure if it's just dead or so....

**Comment by circuitb** [comment]
k

**Comment by mrvux** [comment]
For now seems there's not been any update on that for (months), so not sure if will continue dev on that...
