### ISSUE TITLE
FrustrumTest Validator not working correct when Objects are transformed

### ISSUE THREAD

**Issue by tomeic** [mrvux/dx11-vvvv#219]
You can check in girlpower\11_Layer_Overview.v4p

change the rotation (Transform 2d) and the left most quad will disappear.

**Comment by mrvux** [comment]
Thanks for reporting, could easily reproduce, will look to fix before next release

**Comment by mrvux** [comment]
Ok that's a small edge case, transforming 2d object that way was reversing bounding box.

Fixed in https://github.com/mrvux/dx11-vvvv/commit/563ba64fc956329a2597a5c382ee6c61370c688b
