### ISSUE TITLE
SetSlice (DX11.TextureArray) (dx11)

### ISSUE THREAD

**Issue by newemka** [mrvux/dx11-vvvv#220]
SetSlice (DX11.TextureArray) (dx11) is not working with vvvv beta34

**Comment by mrvux** [comment]
Is that the one from contrib? or SetSlice (DX11.Texture2D) as native? 

Old contrib is obsolete as this node is now part of the main core

**Comment by mrvux** [comment]
SetSlice had been updated in core, so closing this now
