### ISSUE TITLE
KinectMSInteractionNode infs is null

### ISSUE THREAD

**Issue by bboylalu** [mrvux/dx11-vvvv#221]
Hi. First of all, I am not a coder (though I understand / can write a few lines of simple code), I don't know how to debug, but following the tutorial I managed to attach the Visual Studio debugger to vvvv and managed to see that infs is null. By pressing F10 in vvvv I can see that the out pin of Interaction doesn't output anything at all. Sorry for the lack of professionalism in reporting this, but it's pretty much all I can do. I'm running vvvv 45beta34 x86 with Windows 8.1 and Kinect for Microsoft (v 1517). Please review the issue because I really need the grip/grab/grasp gesture and this is the only way I can think of using it. Thank you and again, sorry for the form of this "bug report".

**Comment by mrvux** [comment]
hey, kinect2 is for x64 only, so it will not work on 32 bits build for now.

**Comment by bboylalu** [comment]
It's not a Kinect 2, it's Kinect for Microsoft (v1 - 1517) which only works on x86. Is the KinectMSInteractionNode only for v2? I'm asking because as far as I know it was introduced in SDK 1.7 and I'm using 1.8.

**Comment by mrvux** [comment]
Try to copy the file : KinectInteraction180_64.dll
into either the kinect folder, or in the same folder as vvvv.exe, this might have not made it as copy in the build
