### ISSUE TITLE
Kinect2 Gesture Node

### ISSUE THREAD

**Issue by PRonnenberg** [mrvux/dx11-vvvv#222]
The gesture node is throwing an exception whenever I connect the runtime or start a patch with the gesture node in it. Did you experience anything similar? Are there any infos around? Any workarounds? Any suggestions?

**Comment by mrvux** [comment]
Do you have a valid vgb file? It is required for it to work

**Comment by PRonnenberg** [comment]
Yes I have a couple of different gesture files. The gesture detection itself is fine, it gives me the correct gesture confidence. Any suggestions how to validate the gesture file? But even if there is no gesture file loaded, there is the exception on initialisation. Did you mean that there must be a valid gesture file loaded on startup? I will have a try on that. 
Also, are there any plans or possibilities to make the gesture node spreadable? Cheers

**Comment by mhusinsky** [comment]
i experienced this as well but for me the exception is only thrown when kinect studio is running at the same time and is connected to the service. when it is not running, everything is fine.

but there is one other thing:
the gesture node is only usable for gdb-files containing one gesture. it initializes all the gestures correctly (i.e. gesture names are there) but only the last gesture in the file will be detected. looking at the code it becomes clear why (see [here](https://github.com/mrvux/dx11-vvvv/blob/master/Nodes/VVVV.DX11.Nodes.kinect2/KinectGestureNode.cs#L148-149)). 
do you have any plans to update the code?

**Comment by mrvux** [comment]
Spreadable had been added, about error please submit an issue with a valid example, thanks.
