### ISSUE TITLE
Nested NULL objects

### ISSUE THREAD

**Issue by sunep** [mrvux/dx11-vvvv#224]
not sure if this is a bug report, a feature request or just me not getting it.

Moving an old project to DX11 I need to import 3D files with animation.

with assimp the objects are divided up into null objects with animated objects and static objects. the problem arrives when having nested null objects, there is no way as far as I can see to meaningfully work  with nested null objects in assimp, or am I wrong?

Sune

**Comment by mrvux** [comment]
Issue without example is quite impossible to fix, so please resubmit with example and highlight the problem...
