### ISSUE TITLE
33.7 and 33 failing at splash screen

### ISSUE THREAD

**Issue by wmvoje** [mrvux/dx11-vvvv#227]
Hey just reformatted my computer and updated to Windows 10. Trying to get my vvvv stuff up an running it crashes at splash screen with I have "packs/dx11" in the main directory. 

Any ideas?

From the logger:
[22:00:05.295] vvvv caused error during startup: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Object reference not set to an instance of an object.

Resulting in: An exception occurred while trying to create an instance of type 'VVVV.DX11.Factories.DX11NodesFactory'.

Resulting in: Cannot activate part 'VVVV.DX11.Factories.DX11NodesFactory'.
Element: VVVV.DX11.Factories.DX11NodesFactory -->  VVVV.DX11.Factories.DX11NodesFactory -->  DirectoryCatalog (Path="C:\Users\Willi\Desktop\vvvv_45beta34.1_x64\packs\dx11\factories")

Resulting in: Cannot get export 'VVVV.DX11.Factories.DX11NodesFactory (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory")' from part 'VVVV.DX11.Factories.DX11NodesFactory'.
Element: VVVV.DX11.Factories.DX11NodesFactory (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory") -->  VVVV.DX11.Factories.DX11NodesFactory -->  DirectoryCatalog (Path="C:\Users\Willi\Desktop\vvvv_45beta34.1_x64\packs\dx11\factories")

Resulting in: Cannot set import 'VVVV.Hosting.HDEHost.AddonFactories (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory")' on part 'VVVV.Hosting.HDEHost'.
Element: VVVV.Hosting.HDEHost.AddonFactories (ContractName="VVVV.PluginInterfaces.V2.IAddonFactory") -->  VVVV.Hosting.HDEHost

**Comment by mediadog** [comment]
I used to see this behavior on systems that did not have a DX11-capable 
graphics card.

**Comment by wmvoje** [comment]
My graphics card is dx11 compatible.

Apparently, it was an issue with me using windows' native .zip manager. I used 7zip to un-archive everything and it now works like a dream!
