### ISSUE TITLE
animation and nested null objects

### ISSUE THREAD

**Issue by sunep** [mrvux/dx11-vvvv#231]
not sure if this is a bug report, a feature request or just me not getting it.

Moving an old project to DX11 I need to import 3D files with animation.

with assimp the objects are divided up into null objects with animated objects and static objects. the problem arrives when having nested null objects, there is no way as far as I can see to meaningfully work with nested null objects in assimp, or am I wrong?

as an example, here is an FBX file with nested objects: https://www.dropbox.com/s/ssavl7kq565en9s/awesome_09-nulled.fbx?dl=0

the logic in the file is that some parts are animated and in their own null object and the static parts are in their own null object. inside the null object with animations, there are nested null objects with animations. I have tried extracting it but it gets really hairy.

the solution so far has been to flatten the hierarchy, but it would be great if that wasn't necessary.

Sune

**Comment by mrvux** [comment]
Mm that's how assimp does load (as I get the same in their viewer), so it should go in their issue tracker.

**Comment by sunep** [comment]
I have no idea how to add it to assimps issue tracker, will you do it?

**Comment by mrvux** [comment]
No idea, go to their website, and make a decent repro step on their viewer.

**Comment by mrvux** [comment]
https://github.com/assimp/assimp is the repo by the way, but up to you to submit and provide enough info to them.
