### ISSUE TITLE
MultiScreen (DX11) does not boygroup

### ISSUE THREAD

**Issue by mediadog** [mrvux/dx11-vvvv#234]
In 33.7 and 0.6, when the MultiScreen node is boygrouped, the client machines show it as red.  Seems that it and its sub-patches cannot find the .fx files.

Workaround is to open MultiScreen on the server, double-click on Softedge, and pick it from the list.  The node on the client goes from red to blue immediately.  Open ScreenNumber and do the same for ScreenNumberDX11, and save both patches.

After this these nodes work properly on the clients.  Something to do with the %vvvv% in the node path for .fx files?

**Comment by mrvux** [comment]
Do you have exact same path in your server and clients?
I know there was many issues (not dx11 related, also for assets and dx9) with that aspect.

**Comment by mediadog** [comment]
Yes, exact same environment on all systems.  vvvv can still find the .fx when it is double-left-clicked, so it must be something about how the path was saved in the patch.

I have never noticed paths to nodes having %vvvv% in them before.  I agree it is almost certainly a bug in vvvvv, perhaps that is not expanded on initial load on the clients?  I have lots of other .fx files in my patches that are being loaded just fine on the clients.  But it does appear simply resetting the .fx nodes and saving the patches works around it.

I'll see if I can isolate a vvvv-only test case and submit it as a bug there.

**Comment by gregsn** [comment]
should work now

**Comment by joreg** [comment]
see: https://vvvv.org/forum/lost-paths-on-boygroup-clients
