### ISSUE TITLE
kinect2 stuff

### ISSUE THREAD

**Issue by circuitb** [mrvux/dx11-vvvv#236]
hey Vux! first thanks for this xmas update!

i've played around with Fusion node and  the Geometry InputLayout returns
a Vector2D for both Position and Normals! normal?
[FusionGeomBug (Kinect2 Microsoft) help.zip](https://github.com/mrvux/dx11-vvvv/files/74948/FusionGeomBug.Kinect2.Microsoft.help.zip)

the kinect2 prepose throw errors and crash vvvv
cause of missing prepose dependencies (libz3.dll,BigRationalLibrary.dll,Antlr4.Runtime.v4.5.dll...)
even with those files loading  the Test.app doesn't  produce a gesture output!
[kinect2_prepose.zip](https://github.com/mrvux/dx11-vvvv/files/74955/kinect2_prepose.zip)

take care
C.

**Comment by mrvux** [comment]
About fusion:
Yes it return those two, with a format = R32G32B32Float (3 components float).
Offsets are 0->12, which is fine.

https://github.com/mrvux/dx11-vvvv/commit/626778442ccc819e55a7584993a6c72a9991ac6a
https://github.com/mrvux/dx11-vvvv/commit/a8e6941b8bde2387f0dc2759182e48dc40f5e6db

Fix the references for prepose
