### ISSUE TITLE
Feature Request: DirectWrite text Line Spacing

### ISSUE THREAD

**Issue by YanYas** [mrvux/dx11-vvvv#238]
I don't know if its a feature in the original frame work but being able to adjust the line heght matters almost as much as being able to adjust the letter spacing for typography. If it isn't availabe could you make it possible to separate each line for transformation?

Not an easy task, I'm sure, and thanks for the great library implementation.

H

**Comment by YanYas** [comment]
Perhaps a character counter added to the metric node so one can set up the spacing with the transform tool.

**Comment by mrvux** [comment]
There are options for that but they not in SharpDX, would take a while to have it in there (push, get pull request accepted and have it available)

So I would not count on it soon for now.

To sepearate each line you can split string easily in 4v, so that's rather trivial to do.

**Comment by YanYas** [comment]
Indeed but I would like to do it with the correct text metric so if I
change the spacing for the lines the the words word flow to the next line
in a way that will fit the desired width. This would mean using a dedicated
'wordwrap' node similar to the one implemented for dx9 text.

**Comment by mrvux** [comment]
Won't have time to do tha

**Comment by mrvux** [comment]
Ok actually digging a tad in api, found that you can set spacing at texctformat level, so here it is:

https://github.com/mrvux/dx11-vvvv/commit/2326b3e7cb4462874fd0dfb57ee7531966d851d4

**Comment by YanYas** [comment]
Alright! Cheers Man!!
