### ISSUE TITLE
blur dx11 one line to much?

### ISSUE THREAD

**Issue by princemio** [mrvux/dx11-vvvv#239]
not sure - but i found this:

	float lod=log2(max(R.x,R.y));
	float4 map=tex1.SampleLevel(s0,x,0);map=max(map.x,max(map.y,map.z))*map.a;
	lod=map.x*(Width)*(log2(max(R.x,R.y)));

which imho is calculating twice: log2(max(R.x,R.y));
and since blur is heavy in general - per pixel - multiple passes it could be better only done once:

	float lod=log2(max(R.x,R.y));
	float4 map=tex1.SampleLevel(s0,x,0);map=max(map.x,max(map.y,map.z))*map.a;
	lod=map.x*(Width)*lod;

maybe it helps. 

cheerz

**Comment by mrvux** [comment]
Did you try to profile or check assembly output with fxc?

**Comment by mrvux** [comment]
Just checked output, already optimized away by compiler

**Comment by princemio** [comment]
ah ok thanks for the information - didnt know _ that compiler fixes that easy.
