### ISSUE TITLE
MemoryLeak IndexIndirect (DX11.Drawer)

### ISSUE THREAD

**Issue by katzenfresser** [mrvux/dx11-vvvv#242]
once continously scaling a geometry itself, the memory usage by vvvv continously rises. 

seems as if the allocating memory works well, but not the clearing ;-) 
counterpart nodes probably also affected...

download demo patch: 
https://owncloud.meso.net/public.php?service=files&t=209fe7f32fc508f78dd0d3e49cb48c17

**Comment by mrvux** [comment]
Fixed in https://github.com/mrvux/dx11-vvvv/commit/1414ad95de2490683b47da2047a1193d365d37d3
