### ISSUE TITLE
Feature Request: Sampler (DX11) mirror

### ISSUE THREAD

**Issue by sunep** [mrvux/dx11-vvvv#245]
As the title says, I often make a Sampler (DX11) just to realize that I need Mirror.

Sure it is the default behavior, but if you spread the input it would be nice to have it there so we don't have to use the advanced version.

**Comment by mrvux** [comment]
Ok was rather quick to add so no point to discuss it ;)

Here it is:
https://github.com/mrvux/dx11-vvvv/commit/afd115abea4306d739cba3550be719348139e5a5
