### ISSUE TITLE
Order (DX11.Layer) does not work with Group (DX11.Layer) or Quad (DX11.Layer) output

### ISSUE THREAD

**Issue by mediadog** [mrvux/dx11-vvvv#256]
Appears to only work with the output of DX11.Effect nodes.  Since there is no Group (DX11 Priority), it would be very useful if it worked with DX11.Layer nodes.  Or is there some other way of setting layer priority?

**Comment by mediadog** [comment]
Also seeing what looks to be some odd Order behavior: if I take two Constant nodes each producing one instance, and feed them into a Group and then into Order, the Order node has no effect.  But if I spread some input into the Constant nodes (say color), then the Oder node will set the priority of the two Constant nodes outputs as a set.  So all of the outputs of Constant one will be ahead of all the layers of Constant two, etc.

I'm guessing that Order is working on some information in the layers that is only getting set when there is more than one layer coming out of an effect, and that information is not getting set at all in the DX11.Layer nodes.

**Comment by mrvux** [comment]
Order is to  work at upstream slice level, not layer slices (so to reorder transforms inside a shader node)
To control render order in a dynamic way , use Cons Layer instead of group, the GetSlice (Node) is your friend.

**Comment by mediadog** [comment]
Thanks for the tip about GetSlice (Node) working with DX11 layers, I did not expect that since there are so many other explicit DX11 nodes (like Cons (DX11.Layer)), and I was confused by the node name of "Order (DX11.Layer)", and GetSlice (DX11.Layer Order).  Maybe if the help patch also showed what it does not do, and what to do in those cases I would have figured it out.  (I wish I had time to help with the missing help patches, as I know making them would be an excellent learning experience!)

Is there some reason there is no Group (DX11.Layer Priority)?  That is a really handy way to shift things around in DX9; you can just change the one layer priority to move it instead of having to re-order a list.  Guess I should be able to make one though, thinking about it, now that I know that GetSlice (Node) works.

Thanks again!
