### ISSUE TITLE
Problem with the text nodes in 0.7.1 update

### ISSUE THREAD

**Issue by kbln** [mrvux/dx11-vvvv#263]
the previous version was all right..

windows 10 rus x64
vvvv_45beta34.2_x64/x86

<a href="http://funkyimg.com/view/2gq84" target="_blank"><img src="http://funkyimg.com/i/2gq84.png" alt="Free Image Hosting at FunkyIMG.com" border="0"></a>

**Comment by mrvux** [comment]
You need visual studio c++ 2015 redist. 
https://www.microsoft.com/en-us/download/details.aspx?id=48145
