### ISSUE TITLE
Info (Assimp Mesh) reports incorrect vertices counts

### ISSUE THREAD

**Issue by antokhio** [mrvux/dx11-vvvv#268]
Info (Assimp Mesh) reports incorrect vertices counts
Basically i can see 0 Vertex Meshes in SceneExplorer, however i can not intercept them.
Small test file.... 
[info mesh assimp.zip](https://github.com/mrvux/dx11-vvvv/files/525042/info.mesh.assimp.zip)

**Comment by mrvux** [comment]
Fixed in https://github.com/mrvux/dx11-vvvv/commit/f4abcf364ce88c9626a0f548c051817cc1c6aed0
