### ISSUE TITLE
Cylinder radius1 / radius2 influencing each other

### ISSUE THREAD

**Issue by DominikKoller** [mrvux/dx11-vvvv#270]
Heyhey

Cylinder (DX11) has (I believe) false behaviour regarding its 'Radius 1' and 'Radius 2' inputs. When changing only Radius 1, both ends of the cylinder change size. In this example I'm only changing the value of Radius 1:
![Cylinder1](https://discourse.vvvv.org/uploads/default/original/1X/405cad6aa6f8d4192159d0401d7b9c510c35ad12.gif)

When I half my value for Radius 2 and then divide this by Radius 1, like so:
![CylinderPatch2](https://discourse.vvvv.org/uploads/default/original/1X/3ee2c94a7b991a17c7dd34eb7d3d3c0a064b0ba2.JPG)

Then changing R1 and R2 respectively looks like this, which I think is desired behaviour:
![Cylinder2](https://discourse.vvvv.org/uploads/default/original/1X/e80bd9aa4e8992f13e462595377abebd985c6f6c.gif)

However, then the scale of Radius 1 is off. I had no more time to search for the right workaround so I hacked it by having Radius1 always 1 and scaling in the shaderpass, like so:
![CylinderWorkaround](https://discourse.vvvv.org/uploads/default/original/1X/0ada58b92c535f1530de083081ec6d2c5bb761e4.JPG)

**Comment by DominikKoller** [comment]
Also if I disable CenterY, only the body of the cylinder moves, the caps stay put which destroys the shape.
(won't make a new issue for this small bugger)

**Comment by mrvux** [comment]
Thanks for reporting, this is now fixed in
https://github.com/mrvux/dx11-vvvv/commit/16316dd6b9a0ef0c5cd40c41f9a5b3fd5696f9c9
