### ISSUE TITLE
FileTexture (DX11 2d) marks all textures in a spread as invalid while one is loading

### ISSUE THREAD

**Issue by OtterFamily** [mrvux/dx11-vvvv#271]
[I uploaded a gif](http://imgur.com/a/Alq7e) and held it w/ a monoflop as well to show the phenomenon. I'm not sure if it's a relic of #74 or something else, or if this is just normal, and I'm misunderstanding what it should do.

**Comment by mrvux** [comment]
Yes FileTexture 2d does reload every texture if anything in pin changes, pooled version makes sure to avoid that.
