### ISSUE TITLE
Can't turn off backface culling in DepthStencil (DX11.RenderState Advanced)

### ISSUE THREAD

**Issue by everoneishappy** [mrvux/dx11-vvvv#277]
See help patch for StencilMask (DX11.Layer Write) here:
https://vvvv.org/contribution/stencil-mask

**Comment by mrvux** [comment]
StencilReference (Layer) is deprecated (and removed on last release). You can use StencilReference (RenderState) instead, which removes the problem (and allows to chain other states)

**Comment by everoneishappy** [comment]
Great, thank you muchly :)
