### ISSUE TITLE
R32G32B32_Float troubles

### ISSUE THREAD

**Issue by antokhio** [mrvux/dx11-vvvv#278]
Can't make a texture in R32G32B32_Float format specifically.
Neither TempTarget or tfx pass work for some reason.
Other formats work ok. 
Build from contrib page.

test patch
[texformatcrap.zip](https://github.com/mrvux/dx11-vvvv/files/658797/texformatcrap.zip)
![image](https://cloud.githubusercontent.com/assets/1254168/21285975/c639b23e-c458-11e6-99be-18b1e3003442.png)

**Comment by mrvux** [comment]
Those textures can't be sampled and are not allowed as render targets by dx11 (only as dynamic/immutable)
