### ISSUE TITLE
IndexedGeometryBuffer + CubeSimple (ProjectorTexture Contribution) = Disordered Mesh/Texture

### ISSUE THREAD

**Issue by timpernagel** [mrvux/dx11-vvvv#28]
Colorsound updated the ProjectorTexture-Shader to DX11, but the beam-simulation based on the "CubeSimple" and the new "IndexedGeometryBuffer" behaves strange.

The texture is not mapped correct to the geometry and the mesh disappears from a linear-spreadcount of higher than 23 for x and y.

Not 100% sure but it seems like an IndexedGeometryBuffer-issue.

![image 2013-06-27 at 3 24 18 pm](https://f.cloud.github.com/assets/4920332/735969/7cd1ddce-e306-11e2-8cf7-814e68dfb54a.png)

**Comment by mrvux** [comment]
Ok quite old one and no new info, I'll close for now
