### ISSUE TITLE
Switch (DX11.Texture) is nil if any input is nil

### ISSUE THREAD

**Issue by antokhio** [mrvux/dx11-vvvv#281]
Switch (DX11.Texture) is nil if any input is nil
I know this by design however would be cool to avoid that
[switch nil.zip](https://github.com/mrvux/dx11-vvvv/files/680969/switch.nil.zip)

**Comment by mrvux** [comment]
Makes some sense, this commit https://github.com/mrvux/dx11-vvvv/commit/9d7fbc1b355bf82a70fbd386af13a0bb40202dfd does avoid it (only if Switch pin is single slice)
