### ISSUE TITLE
geomfx in release 0.9.62 behaves weird sinister nasty and ugly

### ISSUE THREAD

**Issue by microdee** [mrvux/dx11-vvvv#286]
when a geomfx (gsfx) created at vvvv startup it works fine. but a freshly created one will cause layer receiving it throwing nullpointer exceptions (in Layout Message output pin) (Object reference is not set to an instance of an object)
video: https://youtu.be/O68ytK-e9yY

**Comment by mrvux** [comment]
Please post samples with proper bug description instead of those, 

Thanks
