### ISSUE TITLE
Broken TextAdvanced(dx11) prevented renderer going Fullscreen & Borderless

### ISSUE THREAD

**Issue by AchimTHISPLAY** [mrvux/dx11-vvvv#287]
No red nodes, I couldn't understand why it wouldn't even go borderless.
Systematically deleted parts of the patch until I found this text node.
Seemed totally fine, in & output pins looked normal.
But after deleting and creating a new one the renderer started bahaving normal.

**Comment by mrvux** [comment]
MM well I can't really to anything without either patch sample or decent repro step, closing for now, if you have way to bring it back feel free to reopen
