### ISSUE TITLE
text(dx11) crops text above size 540

### ISSUE THREAD

**Issue by AchimTHISPLAY** [mrvux/dx11-vvvv#288]
is there a workaround?

**Comment by mrvux** [comment]
This is a setting engine wise (sprite sheet size default), 

so parameter needs to be exposed, but since it's shared by all nodes, I'm not sure where to keep that setting yet (probably one global text node).

**Comment by sebllll** [comment]
maybe a config pin in the text node? still the thing remains, that when one changes the value, it must be updated in all text nodes...

**Comment by mrvux** [comment]
Text engine is shared across nodes,so might be a settings node instead

**Comment by mrvux** [comment]
Also you have several options which are then linked together (texture/glyph size), + mip levels will need to be adjusted accordingly.

One option is to have a "TextEngine" Node, which outputs IFW1FontWrapper instance.

Text nodes then receive a "Text Engine" input pin (and use default IFW1FontWrapper if not connected)

**Comment by mrvux** [comment]
Ok, here is commit that adds that node + pins
https://github.com/mrvux/dx11-vvvv/commit/7f488d5db4e6053cf707a3bcdac2dccfa98c05e2

Sample patch:
[testTextEngine.zip](https://github.com/mrvux/dx11-vvvv/files/739144/testTextEngine.zip)

And release (so no need to compile yourself ;)

https://github.com/mrvux/dx11-vvvv/releases/tag/0.9.65-alpha

**Comment by AchimTHISPLAY** [comment]
thank you vux =)
