### ISSUE TITLE
 Changing input values of geometry primitives in “de-evaluated” subpatch causes memory leak

### ISSUE THREAD

**Issue by bj-rn** [mrvux/dx11-vvvv#289]
50beta35 x64, vvvv-packs-dx11-0.7.1-x64

see also:
https://discourse.vvvv.org/t/changing-input-values-of-dx11-geometry-primitives-in-de-evaluated-subpatch-causes-memory-leak/14645

**Comment by mrvux** [comment]
Fixed in : https://github.com/mrvux/dx11-vvvv/commit/a05f851b23cb3414cada19620f617b217979f804

Also adds a "Keep in memory" pin on the way. 

Pre build : https://github.com/mrvux/dx11-vvvv/releases/tag/0.9.68-alpha
