### ISSUE TITLE
Creating Renderer throws Exception

### ISSUE THREAD

**Issue by sebescudie** [mrvux/dx11-vvvv#297]
_When starting vvvv with an empty patch, creating a Renderer (DX11) throws "Attempted to divide by zero" exception._

With b35.2, dx11-0.9.82 and 1.0.4 are fine (no exception). But with dx11-1.0.7 and onwards, I get the attached Exception details : [exception_dx11_bugreport.txt](https://github.com/mrvux/dx11-vvvv/files/827450/exception_dx11_bugreport.txt). Also tested with b35 and b34.2, same results. After closing the Exception window three times, the Renderer behaves normally.

- OS : Windows10 Entreprise
- GPU : AMD Firepro W9100, same problems with GTX 980Ti
- No Visual Studio installed
- Steps to reproduce : open vvvv, create a Renderer (DX11)

**Comment by mrvux** [comment]
fixed in https://github.com/mrvux/dx11-vvvv/commit/77b234e298a4c6c2a4a41885e461e28c65c9c811
