### ISSUE TITLE
Fatal crash in textlayout

### ISSUE THREAD

**Issue by finechap** [mrvux/dx11-vvvv#298]
When the 'maximum width' pin on the TextLayout (DirectWrite) or (DirectWrite Advanced) gets a negative value it crashes vvvv on my system.

There's no reason to ever make it negative of course, but dutifully reporting the bug anyway. 

![maximum width text dx11 bug_2017 03 12-14 26 00](https://cloud.githubusercontent.com/assets/4467208/23832168/da0e2cd0-072f-11e7-8e79-aedfaccb638a.png)

I have the visual studio 2015 redist recommended to help with text related issues

Running 
vvvv_50beta35.2_x64
vvvv-packs-dx11-1.0.1-x64
Win 10 pro
Geforce GTX 950
Nvidia Driver 376.53

[Maximum Width Text DX11 Bug.zip](https://github.com/mrvux/dx11-vvvv/files/836530/Maximum.Width.Text.DX11.Bug.zip)

**Comment by mrvux** [comment]
Fixed in https://github.com/mrvux/dx11-vvvv/commit/f2ad984bc8a27cdcc49ac3f9f31d0427d920d5e2
