### ISSUE TITLE
Pixel billboard only supports 1 transform

### ISSUE THREAD

**Issue by finechap** [mrvux/dx11-vvvv#299]
Pixel billboard only supports 1 transform in v1.01

Is there any way it could be spreadable?
Then you could supply multiple world transforms to place text for example

**Comment by mrvux** [comment]
Yes billboard is now spreadable

https://github.com/mrvux/dx11-vvvv/commit/7db163f8015b9d3761b37e5e80e10a03835f6a2f

**Comment by finechap** [comment]
Thanks!
