### ISSUE TITLE
SetWindowBounds (Windows) doesn't work with DX11 Renderer

### ISSUE THREAD

**Issue by antokhio** [mrvux/dx11-vvvv#305]
SetWindowBounds (Windows) doesn't work with DX11 Renderer
to test replace renderer in a help patch

**Comment by antokhio** [comment]
`    [PluginInfo(Name = "GetWindowHandle", Category = "WPF", Version = "Windows", Author = "antokhio")]
    public class GetWindowHandle : IPluginEvaluate
    {
        [Input("Input")]
        IDiffSpread<INode> FIn;

        [Output("Output")]
        ISpread<int> FOut;

        public void Evaluate(int SpreadMax)
        {
            FOut.SliceCount = SpreadMax;

            if (FIn.IsChanged)
            {
                for (int i = 0; i < SpreadMax; i++)
                {
                    if (FIn[i] != null)
                    {
                        FOut[i] = (int) FIn[i].Window.Handle;
                    }
                }
            }
        }
    }`

**Comment by antokhio** [comment]
`                for (int i = 0; i < SpreadMax; i++)
                {
                    if (FIn[i] != null)
                    {
                        FOut[i] = (int) FIn[i].Window.Handle;
                    }
                }`
where FIn is 
`        [Input("Input")]
        IDiffSpread<INode> FIn;`

**Comment by mrvux** [comment]
Yes renderer output it's control, not the top window, so need to get the window via node interface.

Main thing is that even with node fully hidden, behaviour is preserved, which is not the case with windows as it might get destoyed
