### ISSUE TITLE
DynamicBuffer (DX11.Buffer Raw) throws exception with empty raw input

### ISSUE THREAD

**Issue by letmp** [mrvux/dx11-vvvv#308]
evaluating a dynamicbuffer with no raw stream connected throws IndexOutOfBounds exception

**Comment by mrvux** [comment]
Ah, was already fixed here : https://github.com/mrvux/dx11-vvvv/commit/4e503b4a4e415ba76ccc618e5fb5ad7b77effeb9

Thought I did something already :)
