### ISSUE TITLE
VVVV.DX11.Nodes.dll kills VVVV, when in nodelist builder mode

### ISSUE THREAD

**Issue by brisance** [mrvux/dx11-vvvv#312]
Verified by a long trial and error session

**Comment by azeno** [comment]
@brisance Does my PR help in this regard? https://github.com/mrvux/dx11-vvvv/pull/310

**Comment by brisance** [comment]
It does!

**Comment by mrvux** [comment]
As a side note PR is now merged, so it will be in next release
