### ISSUE TITLE
nodes are all red :-/

### ISSUE THREAD

**Issue by kamanlam** [mrvux/dx11-vvvv#324]
please bear with my beginner's question...
i've tried everything i could (checked nodelist... visual studio installed),
but all DX11 nodes are still red
could you please help??
![2017-07-14](https://user-images.githubusercontent.com/12643672/28212966-37fe7658-68a4-11e7-952a-b58e0aab47db.png)

**Comment by mrvux** [comment]
Hello, can you run vvvv.exe with the following command line?

vvvv.exe /logstartup

This will create a log file in the vvvv folder, if you can post this it would eventually help.

Also do you have addonpack or other packs installed and working? or is it only dx11 specific?

**Comment by kamanlam** [comment]
thank you mrvux for willing to help!
here is the log file:
[2017.07.22-18.44.07.txt](https://github.com/mrvux/dx11-vvvv/files/1167490/2017.07.22-18.44.07.txt)
and for your information, i do have addonpack installed and working. indeed the problem is only dx11 specific...

**Comment by mrvux** [comment]
Log file doesn't seem to say much (I should actually add little extra log there actually, but no error seems to be reported)

Does it happen with older vvvv versions too (33.7 or 34.2) ?

**Comment by kamanlam** [comment]
![capture](https://user-images.githubusercontent.com/12643672/28494072-d2de850c-6f23-11e7-819a-e56929d82657.PNG)

i could only find 33.15.1 version so i tried it with your b33x release.. unfortunately weird things happen too...nodes are missing
this probably isn't helpful information. sorry about my inability to debug. but then as some most interesting packs are using dx11 nodes, it would be necessary to have dx11 installed for university projects.... if there's anything else i can try, please let me know! thanks so much for having created this and your help

**Comment by mrvux** [comment]
That one is a bit too old, here the link for beta34.2

https://vvvv.org/blog/vvvv45beta34.2

Make sure to match the 64 bits downloads

**Comment by kamanlam** [comment]
thanks so much for your patience! so i tried, unfortunately it doesn't work neither... i tried referencing it in the root page... have add-on pack installed and working...but not dx11 (it doesn't even show up in the category search)....i don't know what's wrong with me or my computer
just in case, i hope these screenshots and log file might be helpful...

[2017.07.23-10.13.00.txt](https://github.com/mrvux/dx11-vvvv/files/1167955/2017.07.23-10.13.00.txt)
![2017-07-23 2](https://user-images.githubusercontent.com/12643672/28497889-1d7f370a-6f92-11e7-818c-f4eefdc8facb.png)
![capture](https://user-images.githubusercontent.com/12643672/28497890-1ebd459e-6f92-11e7-9d9f-67dc42c12fa3.PNG)
![2017-07-23 3](https://user-images.githubusercontent.com/12643672/28497891-25d73592-6f92-11e7-822e-3a8bd4b1f66d.png)

**Comment by mrvux** [comment]
Ah, looking at your folder, it seems you install dx11 folder in vvvv root.

Folder structure should be packs/dx11

**Comment by kamanlam** [comment]
how stupid, but finally - hurray!  : D 
thanks so much mr vux!

**Comment by mrvux** [comment]
No problem, closing issue then!
