### ISSUE TITLE
Layers Disapearing even connected

### ISSUE THREAD

**Issue by colorsound** [mrvux/dx11-vvvv#325]
Hi, 

I have a bunch of layers in a Project mainly using filetexturepool, and upper layer disapear and does not show anymore.

In older dx11 pack and v4 versión all work well in new one the upper layer disapear and doe snto show onless connect only this layer or disable the rest.

**Comment by mrvux** [comment]
This one does fix the issue, so will close.
https://github.com/mrvux/dx11-vvvv/commit/c751f15b456e442a8d1a726230a02894a67f1e34
