### ISSUE TITLE
x86 Assimp issues?

### ISSUE THREAD

**Issue by catvvvveasel** [mrvux/dx11-vvvv#326]
https://www.dropbox.com/s/0a7s8cw1cnk3jdw/Capture.PNG?dl=0

Geometryfile and scenefile are red, I'm guessing an assimp issue?

**Comment by mrvux** [comment]
Do you have all the c++ redist? tried here and looking fine (2012 is for assimp library I think)

**Comment by catvvvveasel** [comment]
Ah ok, it was installed, (setup all green) so I repaired it, and now all is good, could it be corrupted by later updates?
