### ISSUE TITLE
frustum spelling

### ISSUE THREAD

**Issue by mhusinsky** [mrvux/dx11-vvvv#330]
just noticed that you called the "frustum" nodes "frustrum" (one "r" too much)
:)

https://msdn.microsoft.com/en-us/library/ff634570.aspx

**Comment by mrvux** [comment]
Fixed in, https://github.com/mrvux/dx11-vvvv/commit/f2a681cde2875f9c74dc425fce20a5c7754e0d55
which has version info in order not to break patches
