### ISSUE TITLE
possible Memory Leaks

### ISSUE THREAD

**Issue by sebllll** [mrvux/dx11-vvvv#331]
Hello Mr. Vux, 
I think we discovered 2 memory leaks:

1. Temptarget Dispose ([forum post](https://discourse.vvvv.org/t/memory-leak-when-switching-patches-with-texture-output/15984))

This particular issue can be prevented when adding 
`this.FOutBuffers.SafeDisposeAll();`
`this.FOutAABuffers.SafeDisposeAll();`
[here](https://github.com/mrvux/dx11-vvvv/blob/e91757bc7a266019719f7970cfe5e62f7adddbe3/Nodes/VVVV.DX11.Nodes/Nodes/Renderers/Graphics/DX11TempTargetRendererNode.cs#L216)

I'm still not sure if that's the best solution, because there might be a particular reason for the missing dispose functionality...

2. TextureFx Dispose ([forum post](https://discourse.vvvv.org/t/dx11-effect-memory-leak/15999))

This might be a texturefx disposing issue, but a first debugging session was not successfull and i didn't find out, where the leak exactly happens.

thanks,
sebl

**Comment by mrvux** [comment]
1. Indeed, dispose was not called, which was a non issue normally (as the pool gets clears on app quit), but indeed that was an issue in case of create node. Dispose actually funnily fixes the issue, as it leaves a disposed locked resource in the pool, but did it the clean way as to remove it properly from there.

2. Issue was more subtle, as actually was in the effect factory, which was not calling dispose at the end.

Both are fixed now

**Comment by sebllll** [comment]
super! thanks for the quick fix and also for the explanations!

**Comment by sebllll** [comment]
sorry, one more related thing:
the fix you applied in the shaderfactory also has to be done in the AbstractDX11CompShaderFactory for compiled effects...

i tried the exact same thing and it worked [here](https://github.com/mrvux/dx11-vvvv/blob/e91757bc7a266019719f7970cfe5e62f7adddbe3/Core/VVVV.DX11.Factories/AbstractDX11CompShaderFactory.cs#L125):
```csharp
        protected override bool DeleteNode(INodeInfo nodeInfo, IInternalPluginHost pluginHost)
        {
            var plugin = pluginHost.Plugin;

            if (plugin is IDisposable)
            {
                var disposablePlugin = plugin as IDisposable;
                disposablePlugin.Dispose();
            }

            if (this.PluginDeleted != null)
            {
                this.PluginDeleted(pluginHost.Plugin);
            }

            return true;
        }
```

**Comment by mrvux** [comment]
Good point, reopening

**Comment by mrvux** [comment]
Added on precompiled ones too, guess can close again now.
