### ISSUE TITLE
Group Bug

### ISSUE THREAD

**Issue by mhusinsky** [mrvux/dx11-vvvv#341]
hey vux,
there might be a bug when enabling cascaded groups in the new version 1.3. disabling a group further down the hierarchy apparently disables the whole graph...

<img width="536" alt="group01" src="https://user-images.githubusercontent.com/3253299/40608507-fe133614-626b-11e8-9ea5-15a94859e527.PNG">
<img width="544" alt="group02" src="https://user-images.githubusercontent.com/3253299/40608517-034c6ccc-626c-11e8-841e-7f6fc8800e17.PNG">

this is on a radeon pro 560.

**Comment by mrvux** [comment]
Yes this was reported and fixed there : 
https://github.com/mrvux/dx11-vvvv/commit/d24221139d4f08de6719c3a82387fb3d43a4805b

Link for download is issue is pressing : 
https://ci.appveyor.com/project/mrvux/dx11-vvvv/build/1.3.0.2-alpha/artifacts

I guess I'll do a small 1.3.1 with other few fixes

**Comment by mhusinsky** [comment]
great, thanks for the info and update!

**Comment by mrvux** [comment]
As a side note, this is now in contribution page as 1.3.1 (there was also a small annoying texture fx issue , so both deserved an update)
