### ISSUE TITLE
Renderer (DX11 TextureSpread) throws error in relation to viewport

### ISSUE THREAD

**Issue by sebllll** [mrvux/dx11-vvvv#342]
see attached patch. nothing breaks fundamentally, but that `Render Target Stack should now have a size of 0!` message can be annoying.

[Render Target Stack should now have a size of 0.zip](https://github.com/mrvux/dx11-vvvv/files/2140237/Render.Target.Stack.should.now.have.a.size.of.0.zip)

**Comment by mrvux** [comment]
Indeed, there was a missing stack pop when viewport is connected, now fixed
