### ISSUE TITLE
StencilView is not spreadable

### ISSUE THREAD

**Issue by timpernagel** [mrvux/dx11-vvvv#348]
Unfortunately StencilView ist not spreadable. In order to use "StencilView" also for the Renderer TextureSpread, it would need to be spreadable.

**Comment by mrvux** [comment]
Indeed, since that node does not own anything, that was quite trivial to add. This commit adds it : 
https://github.com/mrvux/dx11-vvvv/commit/e7de67b4280438ef02fd6d0b518a701330324732

**Comment by timpernagel** [comment]
That was quick! ＼(^-^)／
