### ISSUE TITLE
Update to official SharpDX 4.2.0

### ISSUE THREAD

**Issue by tebjan** [mrvux/dx11-vvvv#365]
SharpDX 4.2.0 is the last version available, the pack should also use it in order to be compatible with other libraries that have upgraded already.

Is there anything different in the self-compiled version that is used in vvvv dx11?

**Comment by mrvux** [comment]
From now theres no more self compiled version as all changes made it as pull request to official build.

As discussed tho, there are some serious issues with directwrite, so it would require extensive testing

**Comment by tebjan** [comment]
ok, thanks for the feedback. did some tests and everything works fine as it currently is. so closing this.
