### ISSUE TITLE
Appveyor artifacts get deleted soon

### ISSUE THREAD

**Issue by gregsn** [mrvux/dx11-vvvv#366]
Hey, vux!

Those artifacts get deleted in a few days:
https://ci.appveyor.com/project/mrvux/dx11-vvvv/build/artifacts

For now, we'd need to manually upload them here https://vvvv.org/contribution/directx11-nodes .

Can you do it? Or may I? 
Thank you!

**Comment by mrvux** [comment]
Ill look to add new release in the week end indeed, since theres decent amount of fixes in there

**Comment by gregsn** [comment]
Thanks a lot!

**Comment by mrvux** [comment]
For now I made a small dummy commit, so there is a new version in there, until official
