### ISSUE TITLE
videoIn(dx11) goes to black after 10-15secs

### ISSUE THREAD

**Issue by catvvvveasel** [mrvux/dx11-vvvv#44]
Tried in beta 30 and 32, only using my built in web cam on my macbook though...
Resetting doesn't help, disconnecting and reconnecting doesn't solve it either...
I get this exception

------------------------------------------------------------------------------
Exception log with detailed tech info. Generated on 28/08/2013 14:46:34.
You may send it to the application vendor, helping him to understand what had happened.
 Application title: 
 Application file: C:\Users\cat\Desktop\vvvv_45beta30.2_x86\vvvv.exe
------------------------------------------------------------------------------
Exception class: EAccessViolation
Exception message: Access violation at address 00491707 in module 'vvvv.exe'. Read of address 00000061.
Exception address: 00491707
------------------------------------------------------------------------------
Main thread ID = 3956
Exception thread ID = 3956
------------------------------------------------------------------------------
Exception stack
Stack list, generated 28/08/2013 14:46:33
(00145993){vvvv.exe    } [00546993]

**Comment by mrvux** [comment]
Ok this will be replaced by another node, this dshow api doesn't really work well so media foundation will be replacement for it.
