### ISSUE TITLE
Assimp GeometryFile & values < 0.0043

### ISSUE THREAD

**Issue by everoneishappy** [mrvux/dx11-vvvv#69]
Using vvvv b31 x86.  The DX11 Assimp nodes seem to remove any polygons that are smaller then ~.0043 squares in vvvv units.  The same mesh will load and display fine in the current DX9 flavour Assimp.

**Comment by mrvux** [comment]
Not sure if you still have problem, if you do, please submit a relevant model + example patch in a new issue, thanks.
