### ISSUE TITLE
Videoin (DX11.Texture Dshow) wrong vertical resolution input

### ISSUE THREAD

**Issue by circuitb** [mrvux/dx11-vvvv#93]
hey julien just found this strange settings with the
vertical resolution input
the node doesn't take proper width / height settings
for example when my C920 is
800 * 600 the node outputs 640*360
1024 * 768 the node outputs 800*448
1280 * 720 the node outputs 640*360
1280 * 1280 the node outputs 1280*720 
1920 * 1080 the node outputs 1024*576
1920 * 1920 the node outputs 1920*1080 

but no way to 4:3!

**Comment by sunep** [comment]
any news now? how would you recommend getting video into DX11 in 64bit version?

**Comment by mrvux** [comment]
Since this one been removed for now, closing, as new feature is not much relevant, for videoin node, better to create a new issue, so it's a bit clearer for me :)
